name: Magnificent Pipelines of Glory

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Introduction
        run: echo "All glory to Arstotzka!"

  deploy_staging:
    runs-on: ubuntu-latest
    needs: [build]
    environment: staging
    steps:
      - name: Deploy to Staging
        run: echo "This is where I'd deploy to staging if I had one."

  deploy_production:
    runs-on: ubuntu-latest
    needs: [deploy_staging]
    environment: production
    steps:
      - name: Deploy to Production
        run: echo "This production deploy should only happen after approval."

